### ISSUE TITLE
Not rendering

### ISSUE THREAD

**Issue by mikerockett** [math2001/MarkdownLivePreview#10]
![image](https://cloud.githubusercontent.com/assets/4586280/21960988/d259f57e-db05-11e6-8b2f-53705d1ac6fa.png)

ST 3114

**Comment by math2001** [comment]
It's because you need the build 3124 (at least) of Sublime Text to get the *phantoms*. *Help → Check For Update*

**Comment by mikerockett** [comment]
Oh, okay - thanks.
