### ISSUE TITLE
No "live" preview, just the first one.

### ISSUE THREAD

**Issue by msieurtoph** [math2001/MarkdownLivePreview#11]
Hello Math,
Thanks for this plugin.

The preview is working well (it opens the two-panels window when I open an md file)

BUT 

When I type something in the left one (the md file), the preview is not updating anymore. There is a tiny delay, that proves something is processing, but the preview does not change.

FYI : 
* If I save the file, close the window and open the file once again, the preview is showing up with the last update. 
* I am on windows 7, and using SublimeText 3, build 3126.

An idea about the cause of the issue ?

**Comment by math2001** [comment]
Could you have a look in the console, to see if there is an error (`view -> show console`)?

**Comment by msieurtoph** [comment]
Hi
No error in the console. I had a look to it already :)

**Comment by math2001** [comment]
Is there comments in your file? (`<!-- -->`)

**Comment by msieurtoph** [comment]
Nope.
And, as I said, if I save the file and reopen it, the preview is correct ... it is just that the "live rendering" seems not to work anymore.

**Comment by msieurtoph** [comment]
I tried with a new file (an empty one)

The preview is empty at the beginning (normal ;) ), but when I type something in the left panel, I see that the gutter with the line numbers in the right one changes ... but nothing is displayed in the "body"

**Comment by math2001** [comment]
That's really weird... Are you using the default markdown syntax? In your markdown view, open up the console and paste this in:

```python
'markdown' in view.scope_name(0)
```

it should print `True`

**Comment by msieurtoph** [comment]
```
>>> 'markdown' in view.scope_name(0)
True
```

The syntax I use seems very generic. When I tried with an empty md file, I just typed some random text without "signs".

The weird thing is that it seems to process and generate a content, because I clearly see the gutter height expand/reduce to follow the height of the expected content ... but nothing is displayed.

**Comment by msieurtoph** [comment]
And the scroll in right panel seems to follow the move too ...

**Comment by math2001** [comment]
> And the scroll in right panel seems to follow the move too ...

I don't get that... What do you mean?

What plugin to you have installed?

**Comment by msieurtoph** [comment]
I mean : if I typed multiline content, the scroll in the right panel moves to "focus" on the render of the line I am typing, even if the panel does not show anything.

I will try to make some cleaning in my packages and see if it changes something.

Hold the line ! :)

**Comment by math2001** [comment]
oh! That might be because of the color scheme! If the color is the same as the background. It'd be really weird, but try to change your color scheme

**Comment by msieurtoph** [comment]
Ohoh ... Interesting fact :+1: 

When I open an md file, I got the first render as I said.
When I type something in left panel, modification does not show up in right-panel
If I change the color theme just after ... I got the updated render !
If I type something again, the modification does not show up
If I change color theme again, the right panel is updated again.

So I need to change color theme after each modification to get the render updated! 
So weird!

**Comment by math2001** [comment]
What color scheme are you using? Maybe try to restart ST...

**Comment by msieurtoph** [comment]
Already tried to restart ST, a lot ;)
And I use Monokai Bright theme, but it does not depend on the theme I use. I got the issue with all themes I tried.

**Comment by msieurtoph** [comment]
I tried some cleaning of my Packages :
I kept : 
* MarkdownLivePreview
* Package Control
* SideBarEnhancements
 ... then restart ST

But I keep having the problem.

**Comment by math2001** [comment]
Can you send me a screenshot?

**Comment by msieurtoph** [comment]
of what ?
the empty panel ?

**Comment by math2001** [comment]
the mdview and the empty panel (two actually, when it's shown, and when there's nothing)

**Comment by msieurtoph** [comment]
![image](https://cloud.githubusercontent.com/assets/7763445/22141709/94ceb982-def3-11e6-8620-28980ea2a500.png)

**Comment by msieurtoph** [comment]
I finally succeed to get what I want using this package instead :  http://kenokabe.github.io/MarkdownLive/

It does not really fit my needs as I have to start a local server manually, using the ```node app``` command-line, because the automatic mode via ST does not work (maybe a track to explore for our issue : I got a ConnectionRefusedError [WinError 10061])

It's a shame your plugin does not work on my station, because it looks very sexier to have the two-panels directly inside the ST interface, without starting manually an external local server.

I hope you will fix this issue.
Keep me in touch if you do have any idea or test to experiment.

**Comment by msieurtoph** [comment]
I tested the package on another computer and got the same result.

I finally noticed that changing the font size (by scrolling down and up the mouse when holding `Ctrl` key) trigs the rendering update ... I suppose it forces ST to  update the panels views and it looks sufficient to make the rendering working... very very strange.

**Comment by math2001** [comment]
How do you install MarkdownLivePreview? Was it window 7 to? Does the phantoms usually works?

**Comment by math2001** [comment]
paste this in the console, a few times (<kbd>up</kbd> to get the previous command). view.erase_phantoms('hello'); view.add_phantom('hello', sublime.Region(0), '<p>hello world!</p>', sublime.LAYOUT_BLOCK)

Change the HTML to see if it updates properly.

**Comment by msieurtoph** [comment]
Starting with an md file with two "test" lines in it...

Before:
![image](https://cloud.githubusercontent.com/assets/7763445/22167875/610d49da-df69-11e6-8665-18e29688e5cd.png)

After:
![image](https://cloud.githubusercontent.com/assets/7763445/22167906/8c4f37ac-df69-11e6-87d1-0ea8058b6759.png)

Both computer are running Win7 yes. And I install MLP through the Control Package, without any pb..
What is the Phantoms? Is it something about a virtual browser. 
If so, I never really used that kind of thing before: my use of ST is more like an advanced notepad than a complex IDE...

**Comment by math2001** [comment]
The phantoms are these things you just added by typing the code I gave you in the console. They're part of Sublime Text api: they allow you to display (basic) HTML *inside* ST. If you build a python file for example, and there's an error, there'll be a red popup with the error rendered.

And, if you update the `test.md` file, does the phantom go away?

**Comment by msieurtoph** [comment]
**First test:** 
Starting from the last screenshot: 
if I type "re-test" in the left panel (and save)....

![image](https://cloud.githubusercontent.com/assets/7763445/22168442/eaefca08-df6c-11e6-955f-bd5d925eb2ac.png)


**And second test:**
Starting from the same screenshot than the first one.
And if I try to modify the file in an external window...
![image](https://cloud.githubusercontent.com/assets/7763445/22168506/59e89796-df6d-11e6-9e74-36ac2414406a.png)
Then (when focusing on the two-panels window)... 
![image](https://cloud.githubusercontent.com/assets/7763445/22168515/6b441f24-df6d-11e6-80af-448041bd833e.png)

**Comment by math2001** [comment]
So, I'm confused now: does it still show the preview, but just doesn't update it, or stops completely (when you update the `test.md` file)

**Comment by msieurtoph** [comment]
When I open an md file and hit <kbd>Alt</kbd> + <kbd>m</kbd>  : I got the correct preview in the two-panels window. 
But after that, the preview is never updated, whatever I do in the left panel.

The only thing that works is to change theme or change font size. 
These actions seems to "trigg" the preview update, for some reason I don't understand : 

Here you can see that preview is not updated:
![image](https://cloud.githubusercontent.com/assets/7763445/22168933/aab74f5c-df70-11e6-9160-6f015e658b7f.png)
Then I change font-size and the preview gets updated:
![image](https://cloud.githubusercontent.com/assets/7763445/22168983/ff3e5b10-df70-11e6-90ea-b8bd6bc7df1e.png)

**Comment by math2001** [comment]
I don't understand this at all, because the preview isn't even updated (by the plugin) when you change the font size... I'll keep digging

**Comment by math2001** [comment]
Can you retry this, but make sure you change the html (the `hello world!`)

view.erase_phantoms('hello'); view.add_phantom('hello', sublime.Region(0), '<p>hello world!</p>', sublime.LAYOUT_BLOCK)

And see if it gets updated properly.

**Comment by msieurtoph** [comment]
Yes, of course ... I guess I did it wrong the first time.
Here it is:
![image](https://cloud.githubusercontent.com/assets/7763445/22169371/e0a14c6e-df73-11e6-8290-14f4ef9d6140.png)

It only prints the first Hello World ... the Hello World 2 and 3 are not printed.

And If I change font-size, i got the last Hello Wolrd 3 printed:
![image](https://cloud.githubusercontent.com/assets/7763445/22169404/1c1dba70-df74-11e6-91c4-03d1fa5f0cab.png)

And after that if I update the md file (in the left panel), I got this:
![image](https://cloud.githubusercontent.com/assets/7763445/22169430/4350a828-df74-11e6-90db-3905d1364486.png)

And if I change font-size again:
![image](https://cloud.githubusercontent.com/assets/7763445/22169446/65432622-df74-11e6-9f18-26b7660fe94d.png)


Sorry for bugging you with this weird issue.

**Comment by math2001** [comment]
No, it's okay. Now, that's really weird. These phantoms *must* work. Maybe, [revert to a fresh stage](http://www.sublimetext.com/docs/3/revert.html). 

here's a one line "trier" (you should get `hello world! 4`)

```
exec("for i in range(5):\n\tview.erase_phantoms('hello')\n\tview.add_phantom('hello', sublime.Region(0), '<p>hello world! {}</p>'.format(i), sublime.LAYOUT_BLOCK)")
```

**Comment by msieurtoph** [comment]
I am pretty sure your package works well. I am sure it process the preview (the HTML) and push it to the preview panel (so the phantoms are well instantiated and  modified)... but I guess the "visual" part of the panel just needs to be "informed" that its content changed...

Following this idea: changing font-size "informs" the panel to update the "visual" part (because the font size change). And so the previous modifications are obviously taken into account ...   

I just see your previous answer .... I do the test and post again...

**Comment by msieurtoph** [comment]
Here is what I get with your command line:
![image](https://cloud.githubusercontent.com/assets/7763445/22169693/5c60a884-df76-11e6-8298-eb088092d429.png)

And when i change font-size:
![image](https://cloud.githubusercontent.com/assets/7763445/22169698/6a7b37ae-df76-11e6-9515-9a72ac7d9a9c.png)


I am pretty sure you miss a trigger, just to tell the panel to take into account the modifications you made to its content...

**Comment by math2001** [comment]
The trigger is actually the `view.erase_phantoms('hello')`, which is suppose to remove all the phantoms that are named `hello`...

Oh, we're going to test only this. Run this in the console (after having run the command I just gave you):

```
view.erase_phantoms('hello')
```
The phantom should go away

**Comment by msieurtoph** [comment]
yes ... it went away

![image](https://cloud.githubusercontent.com/assets/7763445/22169864/ec064812-df77-11e6-901a-24d4c75dad59.png)

**Comment by math2001** [comment]
Maybe I should add a timeout then... Let's do it in two step:

```
view.erase_phantoms('hello')
```

hit <kbd>enter</kbd>

```
view.add_phantom('hello', sublime.Region(0), '<p>hello world! 5</p>', sublime.LAYOUT_BLOCK)
```

And do those two commands again, but change the `hello world! 5`, and tell me if it's updated. 

Maybe I just need to add a timeout...

**Comment by msieurtoph** [comment]
It printed "Hello world 5", then "hello World 6" :

![image](https://cloud.githubusercontent.com/assets/7763445/22169975/e9a0849c-df78-11e6-978d-d99e9b251831.png)

**Comment by msieurtoph** [comment]
Oh ... you mean the erase function is asynchronous ? 
... and it cannot add a new phantom if an existing has already the same name ?

**Comment by math2001** [comment]
So, yeah, I need a timeout:

```
view.erase_phantoms('hello');sublime.set_timeout(lambda: view.add_phantom('hello', sublime.Region(0), '<p>hello world! 5</p>', sublime.LAYOUT_BLOCK), 250)
```

> Oh ... you mean the erase function is asynchronous ?

I'm not sure, but it's a common problem with ST: to close a file when an other file is being closed, you need to add a timeout, otherwise it crashes for example.

> and it cannot add a new phantom if an existing has already the same name ?

You can, but it'd add a new one, each time you edit your file (you'd end up with 100 phantoms if you type 100 chars 😄 )

**Comment by msieurtoph** [comment]
OK, I think I get it. 
I hope the timeout will solve the pb.

Timeouts are not that nice (I dont like them).
In javascript, you have callback that are called after the action is really done ... This is much better.


But wait a minute : it means my computers are slow to clear the phantoms ??? :(

However I found a post (where somebody was answering you, Math2001) about documentation of erase_phantoms and add_phantom ... He'd hoped you'd rather use Phantom and PhantomSet classes instead. It cannot be the "nicer" solution ?
https://forum.sublimetext.com/t/dev-build-3118/21270/74


I wait for the next release including the timeout (if you want me to test an alpha or beta before releasing : no pb. Give me a link the package and I'll install it and test this issue for you ...)

**Comment by math2001** [comment]
> I hope the timeout will solve the pb.

Did you try to run the code with the timeout?

To be honest, I learned to use phantom with the `add_phantom` since it was the [example given](https://forum.sublimetext.com/t/dev-build-3118/21270). And, I forgot about using `PhantomSet`... 😖 

So, here it is, using PhantomSet:

```
ps = sublime.PhantomSet(view, 'hello')
```

hit <kbd>enter</kbd>

```
ps.update([sublime.Phantom(sublime.Region(0), '<p>hello world! 6</p>', sublime.LAYOUT_BLOCK)])
```

Update the `hello world! 6`, and tell me if it works.

Sorry for keeping you waiting, I just had lunch...

**Comment by msieurtoph** [comment]
Excuse-me ...
Got really busy today! 

Here is the test using the PhantomSet command:
It looks to work perfectly and updates the preview each time, without needing any other actions.
![image](https://cloud.githubusercontent.com/assets/7763445/22178347/ffb30294-e033-11e6-93bd-b11bbb92297e.png)


Here is the test with the timeout:
![image](https://cloud.githubusercontent.com/assets/7763445/22178385/ec9b90ee-e034-11e6-807e-18597270aefc.png)

As long as I can figure it out : the update of the preview seems a bit longer with the timeout than with the PhantomSet command. The PhantomSet command seems to update instantly, when the one with the timeout lasts at least 250ms (the timeout value). 
If I can give my opinion : I would go for the PhantomSet solution.

**Comment by math2001** [comment]
YES! 

> I suggest you to go for the PhantomSet solution.

Of course! I'll push a new tag in minutes.

**Comment by math2001** [comment]
Hum... Harder than I thought it'd be, because I have to save the phantoms in an object. (can't get it from the view, otherwise, I need a timeout 😆 ) But, I'm getting there.

**Comment by math2001** [comment]
I pushed a new tag using those `PhantomSet`. Could you try and tell me if it works?

**Comment by msieurtoph** [comment]
How to ?

When I try to update my packages,  I got 
![image](https://cloud.githubusercontent.com/assets/7763445/22178808/209d8020-e042-11e6-97a2-d196096aa65d.png)

**Comment by math2001** [comment]
You need to wait a bit.

**Comment by math2001** [comment]
If you want, you can remove this package, and install it with `git`, so you just have to run `git pull`

**Comment by msieurtoph** [comment]
Installed by removing package, adding your github repo in Control Package and reinstall the package. Easy!

And it works perfectly.
Thank you very much for your time and your work!

You can close the issue.

**Comment by math2001** [comment]
You solved the problem! You're the one who thought about PhantomSet! So, 👍 for you!!
