### ISSUE TITLE
Enable markdown2 flags [Markdown Tables]

### ISSUE THREAD

**Issue by thatsIch** [math2001/MarkdownLivePreview#12]
Greetings,

from the README I took, that this plugin uses markdown2 for its internals and thus it also delivers the possibility to enable flags like 

https://github.com/trentm/python-markdown2/wiki/tables

Is there a way to specify this via MLP?

Cheers
   Ich

**Comment by math2001** [comment]
That's a good idea! Unfortunately, the Sublime Text's phantoms (the things that renders the HTML) don't support `table`.

What I could maybe do though is format the table so that it's a nice *markdown* table, and then render it in a `<pre>` so that you see a ASCII table... What do you think?

**Comment by ihodev** [comment]
+1 It would be great to have ASCII tables in `<pre>` tag 🎉

**Comment by math2001** [comment]
Ok! Working on it then!

**Comment by thatsIch** [comment]
What I did not know that the Phantom HTML renderer is limited. I thought it could render any kind of HTML >_>

For future reference the minihtml page https://www.sublimetext.com/docs/3/minihtml.html

Since it can render `div`, is rendering a table via CSS not an option?

**Comment by math2001** [comment]
> Since it can render div, is rendering a table via CSS not an option?

Unfortunatley, [no](https://www.sublimetext.com/docs/3/minihtml.html#css)

**Comment by thatsIch** [comment]
you can do it without `display: table` or what are you implying by posting the reference?

**Comment by math2001** [comment]
The supported values of `display` are` inline`, `block`, `list-item`, `none`

**Comment by math2001** [comment]
I pushed some new tags. Could you upgrade and tell if works the way you guys expect it to?

**Comment by ihodev** [comment]
Looks good, this is really better than nothing :wink: :+1:

**Comment by thatsIch** [comment]
> The supported values of display are inline, block, list-item, none

yes, but you can do tables without `display: table`

**Comment by math2001** [comment]
Could you be a bit more descriptive? Indeed, you can, but the way I see it is going to be really hard:

- get the width of each cell: depend on the font and the style (to make the cols aligned)
- because you cannot have `border` in your css, I'd have a make the border with some characters or images.

The way I see it is going to be is pretty hard, full of tweaks and calculation, slow down the render, for something that works fine already...

But, maybe I'm mistaken... How would you do it?
