### ISSUE TITLE
Code blocks highlighting

### ISSUE THREAD

**Issue by Nevitones** [math2001/MarkdownLivePreview#18]
Is there some way to have the code blocks(e.g. ```javascript) highlighted in the preview tab?

**Comment by math2001** [comment]
As I said in here: #17:

> [the preview code] is highlighted with pygments (which, for it to work for everyone, would have to be a dependency). So, this means that I'd have to manually set specific classes to have certain fg/bg/style, depending on the color scheme. Unless you have a really quick solution, I have, for now, not plan on adding this. (I'd gladly accept PR, though)

**Comment by math2001** [comment]
After a quick research, I found this [davinche/pygments-from-tmtheme](https://github.com/davinche/pygments-from-tmtheme) which looks pretty nice, so I'll have a look

**Comment by math2001** [comment]
So, code highlighting is working, but the convertion between the tmtheme/css isn't good at all:

![image](https://cloud.githubusercontent.com/assets/15224242/22845662/d32d48f6-f037-11e6-9645-b3287a28e0fe.png)

It uses the same color, but, as you can see, it doesn't use them where they need to be used...

**Comment by Nevitones** [comment]
Anyway it seems a pretty good start, tks!

**Comment by math2001** [comment]
It's not available right now, it's on [another branch](https://github.com/math2001/MarkdownLivePreview/tree/highlight-fenced-code).
