### ISSUE TITLE
Is it possible to display local images?

### ISSUE THREAD

**Issue by ensaier** [math2001/MarkdownLivePreview#19]
Thanks for your efforts, the plugin is really helpful.
I faced with a problem with displaying of local images, I'm getting 404 pictures instead of my ones.
Is it possible to display local images right from the plugin (i.e. file://), or I need to run a local server to serve pictures to it? I took a glance over the documentation but found nothing.

Probably a screenshot might be clarifying a little bit. Pictures are located in the same folder as markdown is and I'm pretty sure names are correct. I've tried to use `./name` as well, but it didn't help.

<img width="1392" alt="screen shot 2017-02-17 at 10 49 00 am" src="https://cloud.githubusercontent.com/assets/15224242/23083742/45cba2f6-f5b3-11e6-962e-e358ce564df5.png">

**Comment by math2001** [comment]
yep, I tested, loading images doesn't work anymore... Working on it!

**Comment by math2001** [comment]
Got it! A little stupid mistake...
