### ISSUE TITLE
RuntimeError: maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by f8ttyc8t** [math2001/MarkdownLivePreview#2]
Hi,
at first - thank you for sharing this gem with community!

Too bad, it seems there are some issues with it.
As soon I open up a larger document, entire ST3 screen became messed up (see screenshot below).

ST3 itself reports:

> Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 537, in on_deactivated
    v = sublime.View(view_id)
  File "C:\Program Files\Sublime Text 3\sublime.py", line 707, in __init__
    self.selection = Selection(id)
RuntimeError: maximum recursion depth exceeded while calling a Python object
error: plugin_host has exited unexpectedly, plugin functionality won't be available until Sublime Text has been restarted

Any ideas how to handle this? 

Sreenshot: 
![st3-error](https://cloud.githubusercontent.com/assets/1023438/20918379/f6ff6f96-bb96-11e6-90cc-d8ac56f67361.png)

**Comment by math2001** [comment]
It creates the group over and over again, which is weird. 

1. What build of sublime text are you using? 
2. could you give the content of your file (i tried with a fairly big file, every thing was working)

**Comment by f8ttyc8t** [comment]
Hi,
I'm using latest version (build 3126) of ST3, tested with Windows as well as MacOS version.

Because files content is confidential, I replaced it with dummy text. 
But effect stays the same.

[testfile.zip](https://github.com/math2001/MarkdownLivePreview/files/639553/testfile.zip)

**Comment by math2001** [comment]
I've tried with your file, but St does not crash...

Can you re do the manip (so plugin_host crashes), open up the console, and type:

```python
view.settings().get('markdown_preview_enabled')
```

You should have `True`.

```python
view.settings().get('markdown_preview_id')
```

You should have an integer.

Thanks for your time, I really appreciate it. :+1:

**Comment by f8ttyc8t** [comment]
Please find infos attached.
SC did not crash this time, but behave similar.
First file (ZIP) contains console log, at the very end, you'll find output of requested commands (true, 71).

After causing strange behavior, markdown preview does not even open up any more for file used.
But it works like a charm for an other (very small) test file.
I've even restarted ST3, but without any success.

Thanks for YOUR time, because I am the beneficiary of your work :-)

![st3-error_02](https://cloud.githubusercontent.com/assets/1023438/21041494/9ca1abac-bdeb-11e6-8525-db87fea6fb13.png)
[Testfile.problem.zip](https://github.com/math2001/MarkdownLivePreview/files/641498/Testfile.problem.zip)

**Comment by math2001** [comment]
You say that MarkdownLivePreview does not do anything with large file: can you have a look in the console after trying to run the command?

Something that might affect it: what plugins do you have?

The only time that MLP is creating a new view is when the markdown view is modified (that `on_modified` is fired). The problem might be coming from a plugin that would edit the file as soon as you open them. 

Try do disable every plugin except MLP, and see if you still have this issue. To do this quickl:

- go to `Preferences -> Package Settings -> Package Control -> Settings - User`
- copy the list `installed_package`
- open your settings
- paste the list in the `ignored_packages` one.

**Comment by f8ttyc8t** [comment]
Thank you, that solved the issue.
I've disabled all other packages, now it works like expected.

Now I need to find the cause for this, because I depend on some of these plugins...

Anyhow, thank you for support and great tool!

**Comment by f8ttyc8t** [comment]
Hi,
found the (most likely) reason for the probem: "AutoWidth" (https://packagecontrol.io/packages/AutoWidth) plugin.
After disabling it everything works like a charm again.

**Comment by f8ttyc8t** [comment]
Strange behavior occurs again....

But I think I found the root cause:

As soon you are trying to use someting like xxxx&xxx (without blanks), previewer stops working.

Simple test: 
create markdown file (test.mdown) containing content below - works as expected:
> test & test

now change content of file to no longer separate word and & by blank:

> test &test

parser goes nuts.

Maybe this is of help!

**Comment by math2001** [comment]
Cool that it works now. About the `&test`, it's because a the `&` should be replaced by `&amp;` A regex should solve this :smirk:

**Comment by f8ttyc8t** [comment]
Yepp, great it works now.

But replacing & by &amp would not work in normal text (e.g. bread&breakfast would look... interesting in this case)

**Comment by math2001** [comment]
> But replacing & by &amp would not work in normal text (e.g. bread&breakfast would look... interesting in this case)

I don't really understand...

![image](https://cloud.githubusercontent.com/assets/15224242/21064659/2db4fd8c-beb0-11e6-9e8f-654616ec3876.png)

**Comment by f8ttyc8t** [comment]
Hm.
It seems it is still related to my Windows-Installation.
On my Mac, system behaves (now, after disabling AutoWidth) as expected.

Sorry for bothering!

**Comment by math2001** [comment]
So, it's not working on window? (just to make sure we're talking about the same thing: this is about the escaping of `&` right?)

> Sorry for bothering!

You're not bothering me at all!

**Comment by f8ttyc8t** [comment]
It seems your fix has solved that also.
Works in Windows as well as on Mac now.

A big "Thank You!"

**Comment by math2001** [comment]
> Works in Windows as well as on Mac now.

Cool! Thanks to you also!
