### ISSUE TITLE
Font face

### ISSUE THREAD

**Issue by gmask** [math2001/MarkdownLivePreview#20]
Thanks for the great plugin!

I'm attempting to alter the font face. I've tried each of these methods:

**MarkdownLivePreview: Edit Custom CSS File**:
```
body {
    font-family: "CMU Serif";
}
```

I've also tried to target the `p` selector without effect.

**MarkdownLivePreview.sublime-settings -- User**:
```
// Your settings for MarkdownLivePreview. See the default file to see the different options.
{
    "font_face": "CMU Serif",
}
```

Also without effect.

And finally I tried: **MarkdownLivePreviewSyntax.sublime-settings**:
```
{
    "show_menus": false,
    "show_tabs": false,
    "show_minimap": false,
    "gutter": false,
    "rulers": [],
    "word_wrap": true,
    "font_face": "CMU Serif",
}
```

Where all flags work as expected except for the font face.

How can I change the font face of the preview pane?

**Comment by math2001** [comment]
How, sorry... It's not working anymore. The right way to do it is the **first** one. I'll fix this soon.

**Comment by math2001** [comment]
Hum... It was working, just that I hadn't tagged the commit which fixed it, so package control distributed the broken version. Pushed now, it's right [here](https://github.com/math2001/MarkdownLivePreview/releases/tag/v2.4.3)

(sorry for the delay, I forgot about this)
