### ISSUE TITLE
preview of unsaved markdown files

### ISSUE THREAD

**Issue by pkudemonhunter** [math2001/MarkdownLivePreview#21]

**Comment by math2001** [comment]
Might be fixed by [`v3`](https://github.com/math2001/MarkdownLivePreview/milestone/1)

**Comment by math2001** [comment]
Indeed, this is solved only 2 years later, by [`v3.0.0`](https://github.com/math2001/MarkdownLivePreview/releases/tag/v3.0.0) :slightly_smiling_face:
