### ISSUE TITLE
Maximize window on open preview / editing

### ISSUE THREAD

**Issue by aurimus** [math2001/MarkdownLivePreview#23]
Possible? It opens in a corner all the time, little bit annoying.

**Comment by math2001** [comment]
Do you want it to be full screen, or just *maximized*? If it's the second case, it's not possible, that's a reported issue. You can make the window bigger by default (but not maximized unfortunatly) by using [this trick](https://github.com/SublimeTextIssues/Core/issues/1407#issuecomment-256253712)
