### ISSUE TITLE
Document not fully displayed

### ISSUE THREAD

**Issue by fabianmoronzirfas** [math2001/MarkdownLivePreview#26]
Hi @math2001 great package. I'm having an issue though. I have[ this markdown](https://github.com/fabianmoronzirfas/to-markdown-cli/blob/master/README.md) file that is not displayed fully. See the screenshot.  

![bildschirmfoto 2017-04-10 um 08 04 40](https://cloud.githubusercontent.com/assets/315106/24847984/e1d16792-1dc4-11e7-85aa-614e59503e77.png)

Any hints why this might be so?

**Comment by math2001** [comment]
That's probably because of `<br/>`. For some reason, ST breaks with those, it needs `<br />`. This bug is fixed now, though the images are a bit weird...

**Comment by fabianmoronzirfas** [comment]
I left ST-Land a while ago and moved to VSCode-Land. Anyway thanks for making oss
