### ISSUE TITLE
Numbered Lists

### ISSUE THREAD

**Issue by Salzi** [math2001/MarkdownLivePreview#29]
When using numbered lists the preview shows bullet points instead of the correct number. Using sublime build 3126 and newest MarkdownLivePreview from packageControl.

![markdown](https://cloud.githubusercontent.com/assets/4997543/25903170/f79edc28-359b-11e7-967f-2fed5dbcfb9b.png)

**Comment by math2001** [comment]
Awesome message with the preview, thanks for taking the time to make such a clear message!

Indeed, it's a bug, I can reproduce it. I'll look into it right now.

**Comment by math2001** [comment]
Bad news: MarkdownLivePreview isn't the cause. I've tried to explicitely add an ordered list (`<ol>`) and it doesn't work. It's the Sublime Text's phantoms that automatically transform ordered list into unordered ones.

**Comment by Salzi** [comment]
Hi @math2001 and thanks for your work. I use this package quite often.
To be honest I don't understand where the problem is but when its a sublime bug should we send a bug report to the sublime developer?
