### ISSUE TITLE
Preview not updated after downloading image.

### ISSUE THREAD

**Issue by deathaxe** [math2001/MarkdownLivePreview#30]
If remote image resources are added to a markdown file the preview shows a work in progress icon while downloading the file from web. Unfortunately the preview is not automatically updated after finished download. So it looks like download never finishes.

I am using ST3 3139 x64 on Win10.

**Comment by math2001** [comment]
It was something I wanted to do but still haven't. You need to type so that it updates the preview, and only then it checks if the image has been loaded.

**Comment by math2001** [comment]
This is fixed by [`v3.0.0`](https://github.com/math2001/MarkdownLivePreview/releases/tag/v3.0.0) :slightly_smiling_face:
