### ISSUE TITLE
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 2729: ordinal not in range(128)

### ISSUE THREAD

**Issue by ilyen85** [math2001/MarkdownLivePreview#33]
Hi!

I tried to search for a similar bug here, among the issues, but found none. So my problem:

1. Try to open a markdown file (.mdown)
2. Hit alt+m (I'm on OSX Sierra 10.12.5)
3. The Preview tab appears but it's empty

Created a screenshot with the console open:
https://www.dropbox.com/s/h9uesebxft3e65r/Screenshot%202017-07-28%2010.08.29.png?dl=0

Tried with only one h1
https://www.dropbox.com/s/zgvhsbcq3iq80zq/Screenshot%202017-07-28%2010.04.22.png?dl=0

Looked for this error in so, and found something related to python (my python version is 2.7) and character encoding. I'm not sure if it's related to this issue at all, but might help:

https://stackoverflow.com/questions/21129020/how-to-fix-unicodedecodeerror-ascii-codec-cant-decode-byte

Can you please let me know what am I doing wrong?

**Comment by math2001** [comment]
I'm pretty sure it's coming from your custom CSS. Have you created `MarkdownLivePreview.css` in the `User` directory. You might want to check in there...

**Comment by sepich** [comment]
I was hit by the same issue, created PR #35 with fix
