### ISSUE TITLE
make clipboard population optional/configurable

### ISSUE THREAD

**Issue by blalor** [math2001/MarkdownLivePreview#36]
Would it be possible to make the [`set_clipboard`](https://github.com/math2001/MarkdownLivePreview/blob/v2.4.6/MLPApi.py#L71) call optional?  I find that really gets in the way when I need to paste something into a document I'm writing.

**Comment by math2001** [comment]
That was used for debug, sorry. Removed it, thanks for reporting this issue :+1:
