### ISSUE TITLE
Preview files in .sublime-package

### ISSUE THREAD

**Issue by CharlesHugh** [math2001/MarkdownLivePreview#37]
Sublime Text 3:版本 3126
mac版本：MacOS Sierra 10.12.6

1.打开插件“AdvancedNewFile”的Readme.md文件时，
2.Alt(option)+M
结果：原文件内容被清空，LivePreview内容也是空白的

**Comment by math2001** [comment]
Can you please speak in English?

**Comment by CharlesHugh** [comment]
Sorry to take your time to reply.
When I try to preview the Readme.md file of the "AdvancedNewFile" plugin which I download from the Package Control,both the contents of the original .md file and LivePreview content is empty.

Software Versions:
- Sublime Text 3: Version 3126
- mac version: MacOS Sierra 10.12.6

**Comment by math2001** [comment]
How did you open the file? Using `PackageResourceViewer`?

**Comment by CharlesHugh** [comment]
Use:Control+M，just the preview plugin.

**Comment by CharlesHugh** [comment]
And at first，I open the .md file with Sublime Text 3.

**Comment by math2001** [comment]
But how did you originaly open the file in which you pressed `alt+m`?

**Comment by CharlesHugh** [comment]
with Sublime Text，top left corner。

Preferences，Package Setting，AdvabcedNewFile，README

**Comment by math2001** [comment]
Sorry for the delay: yep, it's a bug. It cannot yet open packed files (files in a `.sublime-package` file). Quicky look into it.

**Comment by CharlesHugh** [comment]
Despite this little mistake is a bit annoying, your plugin is really useful, I sincerely hope that you can solve this problem in few days.And have a good day.

**Comment by math2001** [comment]
Sorry, thought I said that:

The `open_file` command doesn't seem to work as mentioned in the unofficial documentation:

> Opens the specified file. Will dynamically open resource files from sublime-package archives as read-only if the specified override file does not exist.

Yet it doesn't open the resource... Might look into it...
