### ISSUE TITLE
Preview not showing at all

### ISSUE THREAD

**Issue by DominikDeak** [math2001/MarkdownLivePreview#38]
When attempting to edit a markdown file, the live preview pane is not showing anything. 

* Sublime v3 (3143)
* Windows 7 x64

The console dumps the following error:

```
Traceback (most recent call last):
  File "C:\Program Files\Sublime Text 3\sublime_plugin.py", line 435, in on_load_async
    callback.on_load_async(v)
  File "MarkdownLivePreview in C:\Users\foo\AppData\Roaming\Sublime Text 3\Installed Packages\MarkdownLivePreview.sublime-package", line 97, in on_load_async
  File "MarkdownLivePreview in C:\Users\foo\AppData\Roaming\Sublime Text 3\Installed Packages\MarkdownLivePreview.sublime-package", line 64, in update
  File "MLPApi in C:\Users\foo\AppData\Roaming\Sublime Text 3\Installed Packages\MarkdownLivePreview.sublime-package", line 76, in show_html
  File "MLPApi in C:\Users\foo\AppData\Roaming\Sublime Text 3\Installed Packages\MarkdownLivePreview.sublime-package", line 40, in markdown2html
  File "functions in C:\Users\foo\AppData\Roaming\Sublime Text 3\Installed Packages\MarkdownLivePreview.sublime-package", line 131, in get_style
  File "functions in C:\Users\foo\AppData\Roaming\Sublime Text 3\Installed Packages\MarkdownLivePreview.sublime-package", line 139, in get_resource
  File "C:\Program Files\Sublime Text 3\sublime.py", line 192, in load_resource
    raise IOError("resource not found")
OSError: resource not found

```

**Comment by math2001** [comment]
Thanks for your clear message. 👍 

It looks like ST can't find your color scheme (which is loaded by MarkdownLivePreview) 🤔 

Could you run these commands in the Sublime Text's console and tell me what the result is?

```
print(view.settings().get('color_scheme'))
```

And then:

```
sublime.load_resource(view.settings().get('color_scheme'))
```

If you haven't changed anything, the second instruction should give you the same OSError (resource not found).

**Comment by DominikDeak** [comment]
Running the two commands produced the following result:
```
>>> print(view.settings().get('color_scheme'))
Packages/Color Scheme - Default/Dawn.tmTheme
>>> sublime.load_resource(view.settings().get('color_scheme'))
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Program Files\Sublime Text 3\sublime.py", line 192, in load_resource
    raise IOError("resource not found")
OSError: resource not found
```

**Comment by DominikDeak** [comment]
Ok, I had a snoop around the `Packages` folder in sublime. Looks like the `Dawn.tmTheme` file is no longer in `Color Scheme - Default.sublime-package`. It was moved into `Color Scheme - Legacy.sublime-package` instead.

**Comment by math2001** [comment]
And what do you get when you run the same 2 commands with your color scheme set to `Packages/Color Scheme - Legacy/Dawn.tmTheme`. (and do you still get the bug)

**Comment by DominikDeak** [comment]
Unfortunately I'm unable to set `Packages/Color Scheme - Legacy/Dawn.tmTheme`.  It doesn't come up in the list when going into *Preferences -> Color Scheme...* menu. 

Manually adding the following line in Sublime settings file did nothing either:
```
	"color_scheme": "Packages/Color Scheme - Legacy/Dawn.tmTheme",
```

I even tried installing the legacy schemes as [instructed here](https://packagecontrol.io/packages/Color%20Scheme%20-%20Legacy), but I'm not having luck. 

I'm quite certain that the legacy package is ok. It's in the path `c:\Program Files\Sublime Text 3\Packages\`. 

That said, I'm bit of a novice with Sublime, so perhaps I'm missing something?

**Comment by math2001** [comment]
> It doesn't come up in the list when going into Preferences -> Color Scheme... menu.

Are you using the latest version of ST? If you are, it's called a quick panel. Otherwise, udpate 😄 .

> I even tried installing the legacy schemes as instructed here, but I'm not having luck.

That's the key thing. You need to install the package that provides the color scheme you want in order to use it.

Have you got package control installed? Otherwise, in the command palette (a quick panel :wink:), which you can bring up by doing <kbd>ctrl+shift+p</kbd>, search for `install`, and should come up with something like `Install package control`. hit enter, wait till it says it successfully installed it.

Then, just search for `install` in the command palette again, it should come up with something `Package Control: Install Package`. Hit enter, wait for the package list to get downloaded (you can see in the status bar the little `=` rebounding between the `[]`). Once it's done, search up in the quick panel `Color Scheme - Legacy`, and hit <kbd>enter</kbd>

Wait for the package to install, and activate your color scheme!

Note: you should use some of the new color schemes. The ones by ihodev are just awesome (DA CS).

**Comment by math2001** [comment]
Hold on: I'm assuming a fair bit here, let me look into it a bit more

**Comment by math2001** [comment]
Got it: you need to enable showing them with a setting:

```
"show_legacy_color_schemes": true
```

**Comment by DominikDeak** [comment]
> Have you got package control installed? 

Yup I've been using Package Control all along. 

> Got it: you need to enable showing them with a setting:

That did the trick. Cheers.

Now back to your original question:

> And what do you get when you run the same 2 commands with your color scheme set to Packages/Color Scheme - Legacy/Dawn.tmTheme. (and do you still get the bug)

This time i'm getting something different in the console: [console.txt](https://github.com/math2001/MarkdownLivePreview/files/1385276/console.txt)

I'm also seeing the preview as well.

**Comment by math2001** [comment]
> This time i'm getting something different in the console: console.txt

Yep, the second command loads the actual color scheme (that's what you're seeing)

> I'm also seeing the preview rendering the markdown as well.

Meaning you don't have any problems anymore?

**Comment by DominikDeak** [comment]
> Meaning you don't have any problems anymore?

Correct, the solution you provided fixed the issue. I can see the live preview working again.

**Comment by math2001** [comment]
> Correct, the solution you provided fixed the issue. I can see the live preview working again.

Awesome!

**Comment by logworthy** [comment]
I had the same issue.  I guess Sublime renamed or relocated the color schemes?  I was able to resolve by going to Preferences -> Color Scheme and selecting my color scheme again.

Before:
```
>>> print(view.settings().get('color_scheme'))
Monokai.sublime-color-scheme
```

After:
```
>>> print(view.settings().get('color_scheme'))
Packages/Color Scheme - Default/Monokai.sublime-color-scheme
```
