### ISSUE TITLE
No preview displayed

### ISSUE THREAD

**Issue by Vi1i** [math2001/MarkdownLivePreview#39]
When using the package, no preview displayed.
I have tried reinstalling and restarting and I have the same issue.

![readme_md](https://user-images.githubusercontent.com/6485370/32806659-542d00f2-c95b-11e7-864a-d1bfd42e202d.png)

**Comment by onedrawingperday** [comment]
Same here...

**Comment by FrankC01** [comment]
Same issue here.

**Comment by mibori** [comment]
Same issue here.

ST3 Build: 3143
MacOS: 10.13.2

**Comment by KhaldiAmer** [comment]
same issue here.

**Comment by ortonomy** [comment]
Same here:
ST3 Build: 3143
MacOS: 10.13

**Comment by niklasingvar** [comment]
Same here:
ST3 Build: 3176
MacOS: 10.13

**Comment by xzl2021** [comment]
Same here:
ST3 Build: 3176
Windows: 10 1803

**Comment by xzl2021** [comment]
Yes, I'm using build 3176. I switched to another default color scheme, then I switched back to monokai, It works.


在 2018年8月13日 at 09:39:10, Mathieu PATUREL (notifications@github.com<mailto:notifications@github.com>) 写到:

@xzl2021<https://github.com/xzl2021> Are you using the latest version of MarkdownLivePreview? It should work.

If it still doesn't:

  1.  Paste your settings
  2.  Paste the console output

Thanks in advance.

**Comment by math2001** [comment]
I'm not sure I understand you correctly, so please reopen if something doesn't work.

**Comment by catalintomescu** [comment]
I'm having the same issue. Here is the last few lines of console output. I hope it helps tracking down the issue.

File "/Users/catalint/Library/Application Support/Sublime Text 3/Installed Packages/MarkdownLivePreview.sublime-package/functions.py", line 139, in get_resource
    return sublime.load_resource(resource)
  File "/Applications/Sublime Text.app/Contents/MacOS/sublime.py", line 192, in load_resource
    raise IOError("resource not found")
OSError: resource not found
