### ISSUE TITLE
Closing the view when the md view is not focused any more

### ISSUE THREAD

**Issue by yangweijie** [math2001/MarkdownLivePreview#4]
![image](https://cloud.githubusercontent.com/assets/1614114/21580573/a8c7393a-d03b-11e6-8e36-16c9a46cd076.png)

Experience improvment.
#
When switch to other tab, tab losing focusing render before shoud hide the preview panel.

**Comment by math2001** [comment]
I've re-done the system. This feature is ~ ok. It's on the branch `image-from-web` for now, but I'll merge it into master soon.

**Comment by math2001** [comment]
I've pushed the changes (with the version `v1.10`!). It's working!

I struggled a lot, but now the solution seems really simple (it is, but I didn't see it straight away 😄 ). Could you try it and tell me what you think?
