### ISSUE TITLE
No edit current file command

### ISSUE THREAD

**Issue by karas1999** [math2001/MarkdownLivePreview#41]
Hi, 
There is no "Edit current file" command in command Palette, Only "Edit custom CSS file". 

Press Option+M or Control+M get nothing either. 

![2017-12-06 10 43 08](https://user-images.githubusercontent.com/12420964/33641971-c4321d56-da72-11e7-8a67-076d1368ce4b.jpg)

How is this happened? 
Is this plugin not able to work with OSX?

**Comment by diniremix** [comment]
nope :cry:  do not work with Gnu/linux
St3 Build 3143
![Imgur MarkdownLivePreview](https://i.imgur.com/yZp6cPQ.png)

**Comment by ldutoit** [comment]
did you find an alternative solution?

**Comment by jorgebrunal** [comment]
yes, @ldutoit 
1. open an Markdown file
2. Open the command palette (`ctrl+shift+p`)
3. Search for: `edit current line `

![](https://i.imgur.com/4YGp4Cf.png)

4. hit <kbd>enter</kbd>

![Imgur](https://i.imgur.com/SEvMcvq.png)

enjoy!

working at with Gnu/linux
St3 Build 3143

**Comment by hairlessbear** [comment]
The command doesn't show up on Windows either.

**Comment by sugarfillet** [comment]
Does it support windows now? Thanks.

**Comment by mojolo** [comment]
It still works on Win10, there may be a conflict with another markdown package if it doesn't.

On my system, I uninstalled the MarkdownEditing package and set md file syntax highlighting to Markdown Extended (as the author mentioned in the readme). 

Alt+M and the command palette method both work now.

**Comment by benjaminv** [comment]
> yes, @ldutoit
> 
> 1. open an Markdown file
> 2. Open the command palette (`ctrl+shift+p`)
> 3. Search for: `edit current line `
> 
> ![](https://camo.githubusercontent.com/c6c916f93ab305c6a43b929c93d9059ab546f6a8/68747470733a2f2f692e696d6775722e636f6d2f345947703443662e706e67)
> 
> 1. hit enter
> 
> ![Imgur](https://camo.githubusercontent.com/8fa65b8ab2e037b9255f8f6a04139a3f0af745c6/68747470733a2f2f692e696d6775722e636f6d2f5345764d6376712e706e67)
> 
> enjoy!
> 
> working at with Gnu/linux
> St3 Build 3143

Thanks but did not see this either.

**Comment by math2001** [comment]
It should work with the last version. Please re-open if it still doesn't :slightly_smiling_face:
