### ISSUE TITLE
does it support mathjax？

### ISSUE THREAD

**Issue by zhizunbao84** [math2001/MarkdownLivePreview#43]

**Comment by RoyiAvital** [comment]
Does this extension support preview of MathJax style math?

I hope the maintainer name implies something :-).

**Comment by math2001** [comment]
Unfortunately no. Math ajax is based on JavaScript, which sublime's Phantoms don't run. Apart from generating an image and then linking it, there's no solution.

If someone really wants this, feel free to PR, but I think it'll slow down everything, and won't benefit that many people...

**Comment by math2001** [comment]
I'm going to close this as it isn't likely that I implement this. Feel free to reopen if you find a smarter solution.
