### ISSUE TITLE
live preview hides rest of code after image with link

### ISSUE THREAD

**Issue by NicholasClark** [math2001/MarkdownLivePreview#44]
I have a file similar to below and it loads the image, but hides the rest of the text afterward. It only shows the preview correctly if I remove the "img" tag or the "a" tag.

----------------------
<a href = http://www.grcalculator.org>
<img src="GRcalculator-logo.jpg" width="250">
</a>

## GRcalculator dockerfile

The dockerfile in this container... etc. etc.

**Comment by math2001** [comment]
It seems to work fine with version 3.0 :slightly_smiling_face: So I'm going to close this, please re-open if it doesn't work for you as well.

**Comment by math2001** [comment]
Oh wait, I just realized a quirk: you have to make sure you do that:

```html
<img src="path/to/image.png" />
NOT
<img src="path/to/image.png">
```

Because otherwise Beautiful soup converts it into this:

```html
<img src="path/to/image.png"></img>
```

And sublime doesn't like that...
