### ISSUE TITLE
Ordered lists are displayed as bullets instead of numbered

### ISSUE THREAD

**Issue by richellis** [math2001/MarkdownLivePreview#45]
Ordered lists are previewed as unordered bullets. They should be numbered according to the [Markdown list syntax documentation](https://daringfireball.net/projects/markdown/syntax#list).  Example:

```
This should be an ordered list, not bulleted:

1. one
2. two
3. three
```

Screenshot:
![screen shot 2018-01-20 at 2 18 28 pm](https://user-images.githubusercontent.com/13336831/35188586-db17f4a8-fdec-11e7-8e31-98e9e1e6a590.png)

**Comment by richellis** [comment]
Sorry, just saw this is a dupe of #29 -- but that was closed as "it's a Sublime Text bug". Could you confirm that this bug has been filed with Sublime HQ?

**Comment by math2001** [comment]
It's right here https://github.com/SublimeTextIssues/Core/issues/1767

**Comment by richellis** [comment]
Thanks! Fingers crossed 🤞

**Comment by math2001** [comment]
:crossed_fingers:
