### ISSUE TITLE
LivePreview for UNSAVED file

### ISSUE THREAD

**Issue by strokie** [math2001/MarkdownLivePreview#47]
Would it be possible to use LivePreview for UNSAVED file?
(I'm very often drafting text in SublimeText then copy / paste somewhere else - and not saving these source files.)

**Comment by yechs** [comment]
[This answer](https://stackoverflow.com/a/20182214) might be helpful

```python
contents = self.view.substr(sublime.Region(0, self.view.size()))
```

**Comment by math2001** [comment]
This is solved by `v3`!
