### ISSUE TITLE
Column Headers not appearing properly

### ISSUE THREAD

**Issue by rjkantor** [math2001/MarkdownLivePreview#49]
The column headers are not appearing properly.  The example below the second column, description does not appear in the preview.

Definition          |    Description |
|:------------- |:-------------------------------------------------------------------------------------------------------|
Travel Manager | 	Can have multiple Advantage #s but they are linked on the BX side to create the interrelationship between each of the unique AA #'s.|

**Comment by math2001** [comment]
Tables are going to be re-implemented, so I'm going to track this in the more general issue #71
