### ISSUE TITLE
Crashes after Installation of Package

### ISSUE THREAD

**Issue by kargok** [math2001/MarkdownLivePreview#5]
First time user of Sublime and packages (and beginner in web development in general), but after I followed the installation instructions for the package, the preview does not work and crashes. Attempted to remove the package via Package Control, but it crashes before I can remove it.  

I do see this "not a directory" error in the console: 
![screen shot 2017-01-05 at 9 53 15 pm](https://cloud.githubusercontent.com/assets/16966584/21708977/1367a348-d392-11e6-974f-9432eea81457.png)

**Comment by math2001** [comment]
Oh! Sorry, haven't thought about this. Working on it (should be fix soon)

**Comment by math2001** [comment]
I pushed a new tag. 

In the command palette: `Package Control: Upgrade Package`, and restart Sublime Text. And now it should work

**Comment by kargok** [comment]
It works!  Thank you so much!
