### ISSUE TITLE
Sequence diagram support?

### ISSUE THREAD

**Issue by dingo-d** [math2001/MarkdownLivePreview#50]
Is there a plan to add support for sequence diagram? Something that can be used like on hackmd.io (I think they are using [mermaide](https://mermaidjs.github.io/) ).

**Comment by math2001** [comment]
For the same reason as MathAjax: it is based on JavaScript, which Sublime's Phantom don't handle. Apart from generating an image from Python and then linking it, I can't think of any solution. Feel free to PR, but I'm closing this as I don't think i'll implement this.

Feel free to reopen if you think of a smarter solution.
