### ISSUE TITLE
Can't seem to preview

### ISSUE THREAD

**Issue by rmwenzel** [math2001/MarkdownLivePreview#52]
Installed the package okay but `alt-m` doesn't bring up a preview window. Also, `MarkdownLivePreview: Edit Current File` doesn't show up in Command Palette. The only thing that does show up in Command Palette is `MarkdownLivePreview: Edit Custom CSS File`.

Using Sublime 3, up-to-date.

**Comment by WillUdstrand** [comment]
Same

**Comment by vanniktech** [comment]
@math2001 have you looked into this yet?

**Comment by math2001** [comment]
What plugins do you have? For the shortcut <kbd>alt+m</kbd> to be enabled, the syntax has to be equal to `text.html.markdown`:

https://github.com/math2001/MarkdownLivePreview/blob/82ad98085faffa4ac9e4f7177beb794b3ddb60db/.sublime/Default.sublime-keymap#L5-L10

**Comment by rmwenzel** [comment]
@math2001 I have MarkdownLivePreview, SublimeLinter, Anaconda, and LaTeXTools installed.

I've just removed and reinstalled the package with Package Control and <kbd>Alt + M</kbd> is now working fine. 

Are you referencing the main key bindings file `Preferences -> Key Bindings`? Or one specific to MarkdownLivePreview? The menu path `Preferences -> Package Settings -> MarkdownLivePreview -> Key Bindings` doesn't exist (as it does for some other packages) and I can't find any key binding or settings file for MarkdownLivePreview on my system.

**Comment by drwanghaipeng** [comment]
The menu path Preferences -> Package Settings -> MarkdownLivePreview -> Key Bindings doesn't exist

**Comment by drwanghaipeng** [comment]
> @math2001 I have MarkdownLivePreview, SublimeLinter, Anaconda, and LaTeXTools installed.
> 
> I've just removed and reinstalled the package with Package Control and Alt + M is now working fine.
> 
> Are you referencing the main key bindings file `Preferences -> Key Bindings`? Or one specific to MarkdownLivePreview? The menu path `Preferences -> Package Settings -> MarkdownLivePreview -> Key Bindings` doesn't exist (as it does for some other packages) and I can't find any key binding or settings file for MarkdownLivePreview on my system.



same problem
