### ISSUE TITLE
the preview don't work

### ISSUE THREAD

**Issue by JACK-HAN** [math2001/MarkdownLivePreview#53]
when i install the plugin the first,it is working,but when i start the sublime text3 again,it doesn't work,and whatever i do anything,it just don't work.press the alt+m,it doesn't work,use the palette, it works.

**Comment by seanxuu** [comment]
same as me

**Comment by danielhadar** [comment]
+1

**Comment by mojolo** [comment]
double check your syntax highlighting. i had to uninstall the MarkdownEditing package as there seemed to be a conflict - neither Alt+M nor the command palette methods worked for me.

using the Markdown Extended syntax highlighting package now and all works as expected.

**Comment by math2001** [comment]
Everything should work fine now, with `v3.0.0`. I'm gonna close this issue, but feel free to reopen if it still occurs :slightly_smiling_face:
