### ISSUE TITLE
Possible to export / copy rendered MD?

### ISSUE THREAD

**Issue by zerweck** [math2001/MarkdownLivePreview#54]
This plugin works great for me. Now that i have a fancy rendered document, i wonder if i could just copy the marked up text out of the preview, but it isn't possible to select anything in there. Currently the only option I see for exporting rendered text is to still use another build system like https://github.com/revolunet/sublimetext-markdown-preview
Will this ever be an option?

**Comment by willow512** [comment]
I'd like to add a +1 to this suggestion, I'd love to be able to just export to html or copy paste to word.

**Comment by math2001** [comment]
You really don't want to copy the [garbage which we have to generate](https://github.com/math2001/MarkdownLivePreview/blob/84fb15aec31de4253d898f4a1ac37e463e3b2a16/markdown2html.py#L39-L96) to fit sublime's quirky minihtml. 

So I don't think that this feature would be within the scope of this plugin, so I'm going to close this issue.

Using `Markdown Preview`, or a package of the like, is still your best shot IMO.
