### ISSUE TITLE
Crashes Sublime Text when trying to show preview tab

### ISSUE THREAD

**Issue by gemisigo** [math2001/MarkdownLivePreview#6]
It crashes Sublime Text when trying to do anything in the tab the markdown text resides after it has been launched from the Command Palette. Simply launching it does not invoke the crash but neither does it show the preview window. Immediately after clicking into the tab shows another tab (the preview) and the editor goes down blazing (watch it [here](http://screencast.com/t/EuGgEgwOnsd)). Console shows nothing.

Any hints on the possible cause and how to avoid it?

**Comment by math2001** [comment]
I pushed a new tag, with the commit above. 

- `Package Control: upgrade package`
- to be safe, restart Sublime Text 3

**Comment by rwols** [comment]
Same problem here with 1.1.2.

**Comment by math2001** [comment]
The version `2` solved this problem, and, although I'm still going to work on this first solution ([a bit more info](https://forum.sublimetext.com/t/markdownlivepreview/24566/15?u=math2001)), I'm closing this issue.
