### ISSUE TITLE
After upgrading sublime3 to the rencent version ,it's just not working

### ISSUE THREAD

**Issue by wuwayne** [math2001/MarkdownLivePreview#60]
Sorry to bother

The newest one is 3.1.1(Build 3176) 14 May 2018.No error comes out, after "Alt+M" just plain.

Try to reinstall,but can not install anymore.

**Comment by nakami** [comment]
same issue for me. issue might be the same as #58 and #57. a workaround is provided in issue #57.

**Comment by MadEmperorYuri** [comment]
This may or may not be related, but I'm unable to install MLP with build 3176. The status bar shows that the package begins installing like any other package, but then it just stops and goes back to showing the insertion point position. If I go back to build 3170, the plugin installs just fine and works perfectly.

**Comment by winstonczc** [comment]
same issue，not work in build 3176

**Comment by math2001** [comment]
Seems to be like #64, I should fix this soon.
