### ISSUE TITLE
Support for [[internal]] and [[url|text]] wiki links?

### ISSUE THREAD

**Issue by TonyGravagno** [math2001/MarkdownLivePreview#61]
Is there a way to render [[internal]] and [[url|other]] syntax as links? This is supported by MediaWiki, DocuWiki, and others. Thanks.

**Comment by math2001** [comment]
I'm not sure how those link work. It doesn't look like regular markdown to me, and hence probably isn't supported by markdown2. So, I'm going to close this. If I'm mistaken, please re-open :slightly_smiling_face:
