### ISSUE TITLE
Numbered Lists Show Up As Bullet Points

### ISSUE THREAD

**Issue by ddm9599** [math2001/MarkdownLivePreview#62]
Numbered lists like:

```
1. Testing
2. Testing 2
```

show up in the preview window as:

```
* Testing
* Testing 2
```

**Comment by math2001** [comment]
It's an issue with Sublime Text. https://github.com/SublimeTextIssues/Core/issues/1767

Since there is nothing MarkdownLivePreview can do about it, I'm closing.
