### ISSUE TITLE
Embedded underscores translated rendered as italics.

### ISSUE THREAD

**Issue by Ambival** [math2001/MarkdownLivePreview#63]
First off, thanks for the wonderful plugin.

Bug: When rendering identifiers with embedded underscores, such as "a_b_c", the underscores are consumed and identifier is rendered as "a<i>b</i>c".

Expected behavior: Identifier would be rendered as "a_b_c".

**Comment by math2001** [comment]
That's a problem with markdown2 (the library that is used internally in order to convert the markdown to html). I've quickly look and I don't think the behavior you're expecting is supported.

**Comment by math2001** [comment]
> First off, thanks for the wonderful plugin.

Hey hey, forgot to say thanks here :slightly_smiling_face: Merci :-)

Unfortunately, there isn't much I can do. If you *really* want that feature, then you should contribute to markdown2 (if you do, I will literally give you a high five :smile: ). But there isn't much this package *should* do to support this, so I'm gonna close this issue.
