### ISSUE TITLE
Preview does not load

### ISSUE THREAD

**Issue by Payero** [math2001/MarkdownLivePreview#64]
I am using Sublime Text Version 3.1.1 Build 3176 on Centos 7. When I open a markdown file I get the following error:
`Traceback (most recent call last):
  File "/mnt/data/apps/sublime_text_3/sublime_plugin.py", line 509, in on_load_async
    callback.on_load_async(v)
  File "/home/oeg/.config/sublime-text-3/Installed Packages/MarkdownLivePreview.sublime-package/MarkdownLivePreview.py", line 97, in on_load_async
    md_view, preview = self.update(view)
  File "/home/oeg/.config/sublime-text-3/Installed Packages/MarkdownLivePreview.sublime-package/MarkdownLivePreview.py", line 64, in update
    show_html(view, preview)
  File "/home/oeg/.config/sublime-text-3/Installed Packages/MarkdownLivePreview.sublime-package/MLPApi.py", line 76, in show_html
    html = markdown2html(get_view_content(md_view), os.path.dirname(md_view.file_name()), md_view.settings().get('color_scheme'))
  File "/home/oeg/.config/sublime-text-3/Installed Packages/MarkdownLivePreview.sublime-package/MLPApi.py", line 40, in markdown2html
    html = '<style>\n{}\n</style>\n'.format(get_style(color_scheme))
  File "/home/oeg/.config/sublime-text-3/Installed Packages/MarkdownLivePreview.sublime-package/functions.py", line 131, in get_style
    css += pygments_from_theme(get_resource(color_scheme))
  File "/home/oeg/.config/sublime-text-3/Installed Packages/MarkdownLivePreview.sublime-package/functions.py", line 139, in get_resource
    return sublime.load_resource(resource)
  File "/mnt/data/apps/sublime_text_3/sublime.py", line 192, in load_resource
    raise IOError("resource not found")
OSError: resource not found
`

Any Suggestion?  Thanks,

Oscar

**Comment by fmilicchio** [comment]
I confirm the issue, @martadelyon reported on W10 and I add macOS 10.13.6, with the exact screenshots and behavior on the mac.

**Comment by ErikTollefsrud** [comment]
Someone mentioned in a [different post](https://github.com/math2001/MarkdownLivePreview/issues/57) that installing and activating the Monokai-Extended color scheme made the preview work for them.
I just tried that and it works. This could maybe serve as a work-around for some people.

**Comment by benmarten** [comment]
+1 :(

**Comment by stefanovazzocell** [comment]
+1

**Comment by Miladiouss** [comment]
First I installed SublimeText-Markdown/MarkdownEditing from GitHub, then I installed MarkdownLivePreview. It was working like a charm. After removing MarkdownEditing, I wasn't able to get live previews anymore, no matter how many times I re-installed MarkdownLivePreview.
I am using Ubuntu 16 and Sublime 3.

**Comment by Crescive** [comment]
Same here. Fresh install of MarkdownLivePreview and not working at all. Have the latest trial build of Sublime Text 3

**Comment by Attache** [comment]
After installing MarkdownEditing, the MarkdownLive Preview works.

**Comment by Attache** [comment]
![image](https://user-images.githubusercontent.com/13183806/43300646-eeac65b4-9192-11e8-9436-880e6426f7b3.png)
You can change the schema by MarkdwonEditing settings file. There is a "color_scheme" option in Markdown.sublime-settings file.

**Comment by WytheC** [comment]
Thanks! I'll try this. By the way, I think you should take notice of your personal information when you upload a picture.

**Comment by Miykoll** [comment]
> Someone mentioned in a different post that installing and activating the Monokai-Extended color scheme made the preview work for them.
I just tried that and it works. This could maybe serve as a work-around for some people.

Did the trick for me!

**Comment by kevingoldsmith** [comment]
Installing and activating Monokai-Extended did not work for me on OSX, and after installing MarkdownEditing, Alt-M didn't work to launch MarkdownLivePreview anymore and MarkdownLivePreview: Toggle isn't available in the command window at all.

**Comment by ZiHaoRan** [comment]
The project has not been updated for a long time

**Comment by math2001** [comment]
No it hasn't... The main reason being that I've moved to vim.

After a quick look, this issue is caused by MLP failing to load the color scheme. There's definitely a problem when loading the newer color schemes (`.sublime-color-scheme`) since it's in JSON, and the old color schemes use to be `.tmTheme`, in XML.

So when MLP loads the current color scheme in order to get the right colors to highlight the `<pre>` blocks with the right colors, it tries to load the current color scheme with a XML parser.

I think I'm just going to remove the highlighting part. It's not that crucial, and I don't have the time to load make a converter of a `.sublime-color-scheme` to a pygment css.

**Comment by ABrayman15** [comment]
Installing the Monokai-Extended package - closing sublime text - reopening sublime and the file, then alt+m WORKED! Thank you!

**Comment by LeiRui** [comment]
+10086
