### ISSUE TITLE
Text inside two "~~~~" is not rendered in box

### ISSUE THREAD

**Issue by Balussery** [math2001/MarkdownLivePreview#67]
Thank you for this awesome tool. I would like to address a bug. If I want to put a text in a grey box I put the text sandwiched between a pair of four Tilda (~~~~ text ~~~~) but not working in the preview. 

thank you.

**Comment by math2001** [comment]
To put the text in a grey box, I think you have to use something like this:

```
Some regular text, or `in a grey box`
```

(notice the <code>\`</code>)
