### ISSUE TITLE
Math equations written in markdown is not being rendered

### ISSUE THREAD

**Issue by ajaygunalan** [math2001/MarkdownLivePreview#68]
I want to write math equations, but it's not being rendered, for example, when I write:

    $\rho c \frac{\partial T}{\partial t} = \frac{\partial q}{\partial x}$
    $\alpha$
It remains the same in the Preview window, it's not being rendered as a Math equation in Preview Window.

**Comment by math2001** [comment]
Discussion is over there: https://github.com/math2001/MarkdownLivePreview/issues/43
