### ISSUE TITLE
Looks like a filename, not markup

### ISSUE THREAD

**Issue by gelldur** [math2001/MarkdownLivePreview#70]
```
/home/gelldur/.config/sublime-text-3/Packages/bs4/all/bs4/__init__.py:198: UserWarning: "b'.'" looks like a filename, not markup. You should probably open this file and pass the filehandle into Beautiful Soup.
  '"%s" looks like a filename, not markup. You should probably open this file and pass the filehandle into Beautiful Soup.' % markup)
font face "Times" could not be found, defaulting to "Monospace"
```

README file: https://github.com/gelldur/EventBus/blob/3688c145cbb6ff4f96bbb4a494a7b62eff6591d1/README.md

**Comment by gelldur** [comment]
![image](https://user-images.githubusercontent.com/175790/45264028-ba7fbc80-b435-11e8-95de-1d18642861f9.png)

**Comment by math2001** [comment]
I tried to reproduce this, but didn't get the error message. I'm hence going to assume that this is no longer relevant to the latest version (it seems to work fine  :slightly_smiling_face: with it)
