### ISSUE TITLE
HTML and XML code blocks do not render properly

### ISSUE THREAD

**Issue by markwdickson** [math2001/MarkdownLivePreview#72]
I was recently trying to preview a document where I have some XML code blocks for SOAP web service calls and found that the Markdown Preview handling of XML and HTML style elements is wonky at best.  As you can see in the example image below, some sections only show pieces of the code, while other sections disappear completely.  I understand there is likely HTML generation happening for the preview, but perhaps the input needs to get escaped?  I even tried wrapping my code block in HTML comment tags, with no change.

![image](https://user-images.githubusercontent.com/1031162/46093959-bcac7f80-c186-11e8-85ab-4d83560a1b9c.png)

**Comment by cortl** [comment]
Looks like it doesn't work with Java either

**Comment by math2001** [comment]
It seems to work fine with the version `3.0` :slightly_smiling_face: I'll close this, please reopen if it doesn't for you.
