### ISSUE TITLE
TFS row/col query string params removed from preview links

### ISSUE THREAD

**Issue by wscarter** [math2001/MarkdownLivePreview#75]
Links to specific functions in Team Foundation Server contain a row/col query string param.  The preview link in MarkdownLivePreview for some reason removes them from the rendered link location.  Issue does not appear to be on TFS side, as other markdown renderers link correctly.

**Comment by math2001** [comment]
Could you give an example of such a link? I have rewritten the whole package, and there are a lot less quirks about manipulating the final html (although there still are some because sublime's minihtml is really quirky), so I'm gonna assume it works now. If it doesn't, please reopen this issue.
