### ISSUE TITLE
two major bugs in mac version

### ISSUE THREAD

**Issue by lrdegeest** [math2001/MarkdownLivePreview#77]
1. contrary to what is said in the documentation, there is no way to toggle live preview using `cmd+shift+p`. the only way to view a live preview of a markdown file is to change user preferences so all markdown files are defaulted to open with a live preview (`"markdown_live_preview_on_open": true`)
2. ordered lists are coerced to unordered lists.

**Comment by math2001** [comment]
> ordered lists are coerced to unordered lists.

This is because sublime text doesn't support ordered list in Phantoms (see https://github.com/SublimeTextIssues/Core/issues/1767)

> contrary to what is said in the documentation, there is no way to toggle live preview using cmd+shift+p

This should work now with the latest version, although the second behavior (preview on open) is not yet implemented.
