### ISSUE TITLE
local images shown as 404 again

### ISSUE THREAD

**Issue by mediter** [math2001/MarkdownLivePreview#81]
macOS 10.14.2 (18C54) with Python v. 2.7.10

Sublime Text v. 3.1.1 build 3176

MarkdownLivePreview v. 2.4.9

**Comment by BloodPupil** [comment]
You  can use <img> tag to achieve that.
```
 <img src='local path'>comments</img> 
```

**Comment by math2001** [comment]
Remote, absolute path and relative path images should work fine now:

```markdown
![my alt text (in case the image doesn't load)](path/to/image.png)
```
