### ISSUE TITLE
what is the MarkdownLivePreview.css for? 

### ISSUE THREAD

**Issue by michapixel** [math2001/MarkdownLivePreview#89]
doesn't it style the livePreview? Seems not. Would it be possible to do this?

**Comment by michapixel** [comment]
i mean thr right side, the real (browser) preview :)

**Comment by math2001** [comment]
Yes it does :) But you have to be aware that it's rendered in Sublime Text's Phantom, which isn't quite the same as a regular web browser. The phantom's documentation is on the [minihtml page](https://www.sublimetext.com/docs/3/minihtml.html).

Would you want to contribute and submit a PR explaining this in a bit more details in the [markdown live preview's documentation](https://math2001.github.io/MarkdownLivePreview/#custom-css)?

**Comment by rafaelbeckel** [comment]
For me it doesn't work as well. I'm using Material theme, but I want a white background in the preview. Also, the preview overflows the container.

I have tried: 

```
html, body {
    background-color: #fff !important;
    width: 100%;
    overflow: wrap;
}
```

and it doesn't affect the viewer, even when I restart Sublime.

**Comment by math2001** [comment]
@rafaelbeckel you have to keep in mind that we aren't rendering in a browser, but Sublime's very quirky and limited [minihtml](https://www.sublimetext.com/docs/3/minihtml.html).

Just to keep everything super clear:

> doesn't it style the livePreview?

It does, but you can only use very few CSS properties (see minihtml link).

**Comment by rafaelbeckel** [comment]
Thanks for the explanation! I’ve skimmed minihtml’s docs and it seems `background-color` property is included. Maybe I’m missing something.
