### ISSUE TITLE
alt+m not opening MarkdownLivePreview

### ISSUE THREAD

**Issue by casajake** [math2001/MarkdownLivePreview#96]
alt+m doesn't open a preview. I can use the Command Palette to open it, but it's much slower. I've reinstalled MarkdownLivePreview with the same results. I'm on a Windows 10 machine. Sublime Text Ver. 3.2.2, Build 3211

**Comment by math2001** [comment]
I released a new version, and I think this shortcut annoyed a few people. So I have decided to remove it, and let people choose for themselves. Though I forgot to put that in the README... If you liked this shortcut, all you have to do is add this to your keybinding file:

```json
{
  "keys": ["alt+m"],
  "command": "open_markdown_preview"
}
```

**Comment by casajake** [comment]
Thanks!

**Comment by xiejiankangc** [comment]
Thanks！
