### ISSUE TITLE
Numbered lists are rendered as unordered lists

### ISSUE THREAD

**Issue by anied** [math2001/MarkdownLivePreview#97]
# Numbered lists are rendered as unordered lists

**Steps to reproduce:**

1. Save a file called `test.md` with the following contents:
    ```markdown
    # test

    1. one
    1. two
    1. three
    ```
1. Attempt to live preview the document.

**Expected:** The items prepended with `1.` will be rendered as an ordered (numbered) list
**Actual:** The items are instead rendered as an unordered (bulleted) list

It's been a while since I busted out some python but I could take a crack at this if needed-- at a glance I'm thinking [`_do_lists`](https://github.com/math2001/MarkdownLivePreview/blob/9fe736902989c2921bd882c22054e0294f708efc/lib/markdown2.py#L1737) is the correct place to start, but I'd happily take any direction.  Or if this is a new, critical bug then maybe it is best tackled by the creator.  Let me know how I can help or if any additional info is needed.

**Comment by math2001** [comment]
That's a very neat bug report :-) Thank you for wanting to contribute! Unfortunately, this is a known bug that isn't the responsibility of the markdown parser but of Sublime Text itself. It [renders numbered lists as dot lists](https://github.com/sublimehq/sublime_text/issues/1767), hence there is nothing MarkdownLivePreview can do about it... So I'm going to close this.

As this is the [fifth bug report on this](https://github.com/math2001/MarkdownLivePreview/issues?utf8=%E2%9C%93&q=is%3Aissue+numbered), it should probably should be mentioned somewhere... I'm thinking in the `README.md`, but I'm not sure... Where do you think would be a place you would have seen straight away?

**Comment by anied** [comment]
Thanks for the prompt reply 🙂

I checked the [project homepage](https://math2001.github.io/MarkdownLivePreview/) as well as the [Github readme](https://github.com/math2001/MarkdownLivePreview) for any reference before posting the bug. I'd say that the latter would probably be a good place to note it-- maybe a short list under the heading of "Known Issues/Limitations".  I think it is a fair and reasonable expectation that users review the readme before opening a bug to see if their issue is already noted there.

The package is great, thanks very much.  I'll see if I have bandwidth for either of the issues noted above-- if so, I'll make a comment in the issue to make you aware that I am working on it.  Thanks again!

**Comment by math2001** [comment]
> The package is great, thanks very much.

Thank you :slightly_smiling_face: 

>  I'll see if I have bandwidth for either of the issues noted above-- if so, I'll make a comment in the issue to make you aware that I am working on it.

That's perfect :ok_hand:
